### ISSUE TITLE
 addMenuItem(): commandID not found: /* Comment

### ISSUE THREAD

**Issue by wormeyman** [avleze/brackets-doxygen#2]
I'm getting that error in the console.

**Comment by avleze** [comment]
Hello, I made this little plugin for fun.I don't know how exactly Brackets works, so if you could say me where I can find the console in Brackets, I'll try to correct the error.

Very thanks for report this error.

**Comment by wormeyman** [comment]
Debug - Show developer tools

**Comment by avleze** [comment]
Ok now is fixed.

Thank you very much :)
